# Generated by Django 5.2.7 on 2025-10-04 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_post_autothor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autothor',
            new_name='author',
        ),
    ]
