# Generated by Django 5.2.7 on 2025-10-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_project_projectfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfile',
            options={'verbose_name': 'Медиа проекта', 'verbose_name_plural': 'Медиа проектов'},
        ),
        migrations.AlterModelTable(
            name='projectfile',
            table='media_desing_project',
        ),
    ]
